disable_functions =
max_execution_time = 30
max_input_time = 60
memory_limit = 128M
display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
extension_dir = "C:\Users\Atharv\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=php_openssl.dll
extension=php_sockets.dll
extension=php_mbstring.dll
extension=php_curl.dll
[mail function]
SMTP = localhost
smtp_port = 25
