services:
  - type: web
    name: quemahtech-ems
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && node build.js
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: firebase-service-account.json
      - key: ADMIN_USERNAME
        value: quemahtech
      - key: ADMIN_EMAIL
        value: atharvashishn@gmail.com
      - key: APP_NAME
        value: Quemahtech EMS
